---
# Choose One
# kind: "ClusterRoleBinding"
# kind: "RoleBinding"
metadata:
  name: {{ template "<CHARTNAME>.fullname" . }}
  labels:
    app: {{ template "<CHARTNAME>.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "__ROLE_NAME__"
subjects:
  - kind: "ServiceAccount"
    name: "__SERVICE_ACCOUNT_NAME__"
    namespace: "{{ .Release.Namespace }}"
